- hosts: localhost
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: Include openscap role
      include_role:
        name: roles/openscap
      when: openscap_hardening|bool
