---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"

- name: Debug variables
  debug:
    var: vars

- name: Include openscap install tasks
  ansible.builtin.include_tasks: openscap.yml

