---
- name: Update packages cache
  ansible.builtin.package:
    update_cache: yes

- name: install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ deps }}"

- name: create temporary directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: '0755'

# clone ComplianceAsCode repo
- name: Clone ComplianceAsCode repository
  git:
    repo: "https://github.com/ComplianceAsCode/content.git"
    dest: "/tmp/content"
  when: is_ubuntu_22 or is_debian_12
  
- name: Make xccdf profile
  command:
    chdir: "/tmp/content/build/"
    cmd: "{{ item }}"
  loop:
    - "cmake ../"
    - "make -j4 {{ os_profile }}"
  when: is_ubuntu_22 or is_debian_12

- name: Execute the remediation using standard profile
  command:
    chdir: "/tmp/content/build/"
    cmd: "sudo oscap xccdf eval --remediate --profile {{ security_profile }} --report /tmp/oscap_report.html {{ ssg_file }}"
  ignore_errors: yes
  when: is_ubuntu_22 or is_debian_12
  
- name: Execute the remediation using standard profile
  command:
    cmd: "sudo oscap xccdf eval --remediate --profile {{ security_profile }} --report /tmp/oscap_report.html /usr/share/xml/scap/ssg/content/{{ ssg_file }}"
  ignore_errors: yes
  when: is_rocky_9 or is_rocky_8 or is_rhel_8 or is_rhel_9

- name: Remove ComplianceAsCode content folder
  file:
    path: "/tmp/content"
    state: absent
  when: is_ubuntu_22 or is_debian_12

- name: Cleanup installed packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ deps }}"
  when: is_ubuntu_22 or is_debian_12
