---
- name: Update packages cache
  ansible.builtin.package:
    update_cache: yes

- name: install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: 
    - "{{ deps }}"

- name: create temporary directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: '0755'

# clone ComplianceAsCode repo
- name: Clone ComplianceAsCode repository
  git:
    repo: "https://github.com/ComplianceAsCode/content.git"
    dest: "{{ tmp_dir }}"
  when: is_ubuntu_22 or is_debian_12
  
- name: Make xccdf profile
  command:
    chdir: "{{ tmp_dir }}/content/build/"
    cmd: "{{ item }}"
  loop:
    - "cmake ../"
    - "make -j4 {{ os_profile }}"
  when: is_ubuntu_22 or is_debian_12
  
- name: Execute the remediation using standard profile
  command:
    cmd: "oscap xccdf eval --remediate --profile {{ security_profile }} --report {{ report_dir }}/oscap_report.html {{ ssg_file }}"
    chdir: "{{ tmp_dir }}/content/build/"
  ignore_errors: yes

- name: Remove ComplianceAsCode content folder
  file:
    path: "{{ tmp_dir }}"
    state: absent

- name: Cleanup installed packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ deps }}"
  
