---
report_dir: "/tmp"
tmp_dir: "/tmp/ComplianceAsCode"
os_profile: "debian12"
deps:
  - wget
  - cmake
  - libdbus-1-dev
  - libdbus-glib-1-dev
  - libcurl4-openssl-dev
  - libgcrypt20-dev
  - libselinux1-dev
  - libxslt1-dev
  - libgconf2-dev
  - libacl1-dev
  - libblkid-dev
  - libcap-dev
  - libxml2-dev
  - libldap2-dev
  - libpcre3-dev
  - swig
  - libxml-parser-perl
  - libxml-xpath-perl
  - libperl-dev
  - libbz2-dev
  - librpm-dev
  - g++
  - libapt-pkg-dev
  - libyaml-dev
  - libxmlsec1-dev
  - libxmlsec1-openssl
  - git
  - make
  - libxml2-utils
  - python3-setuptools
  - xsltproc
  - openscap-utils
  - python3-openscap

security_profile: xccdf_org.ssgproject.content_profile_standard
ssg_file: "ssg-debian12-ds-1.2.xml"
